# Build pdf2htmlEX for Windows
name: Build pdf2htmlEX for Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
    with:
      msystem: MSYS
    - shell: msys2 {0}
      run: |
        makepkg-mingw -sCLfc --noconfirm --noprogressbar
        pacman --noconfirm -U mingw-w64-*-any.pkg.tar.xz
    - run: |
        set MSYSTEM=UCRT64
        msys2 -c '<command to test the package>'
