# Build pdf2htmlEX for Windows
name: Build pdf2htmlEX for Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        sys:
          - mingw64
          - mingw32

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set java location in file javalocation.txt
        shell: pwsh
        run:  Get-Command java  | select Source > javalocation.txt

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: >-
            diffutils findutils make patch tar pkgconf git
          pacboy: >-
            gcc:p
            gmp:p
            ntldd-git:p
            gettext:p
            libiconv:p
            cmake:p
            ninja:p
            ccache:p
            cc:p
            gobject-introspection:p
