# Build pdf2htmlEX for Windows
name: Build pdf2htmlEX for Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        sys:
          - mingw64
          - mingw32

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build pdf2htmlEX on msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: false
          install: >-
            diffutils findutils make patch tar pkgconf wget upx

          #pacboy: >-
            #gcc:p gmp:p ntldd-git:p gettext:p libiconv:p cmake:p
            #ninja:p ccache:p cc:p gobject-introspection:p
            #libspiro:p cairo:p zlib:p libpng:p giflib:p libjpeg-turbo:p
            #libxml2:p openjpeg2:p freetype:p fontconfig:p glib2:p
            #pixman:p harfbuzz:p ttfautohint:p
      - shell: msys2 {0}
        run: sh myjava.sh
      #- shell: cmd
        #run: |
          #ReleasePackage\bin\pdf2htmlEX.exe --version
