# Build pdf2htmlEX for Windows
name: Build pdf2htmlEX for Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Java location command-line
      shell: pwsh
      run:  Get-Command java  | select Source
    - uses: msys2/setup-msys2@v2
    - run: powershell -Command "Get-Command java  | select Source" | grep java
