# Build pdf2htmlEX for Windows
name: Build pdf2htmlEX for Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set java location in file
      shell: pwsh
      run:  Get-Command java  | select Source > javalocation.txt
    - uses: msys2/setup-msys2@v2
    - shell: msys2 {0}
      run:  sh mypdf2htmlbuild.sh
