# Build pdf2htmlEX for Windows
name: Build pdf2htmlEX for Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: MSYS2
        uses: msys2/setup-msys2@v2
        run: uname -a
